# Generated by Django 5.1.3 on 2024-12-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctordetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='available_days',
            field=models.CharField(blank=True, help_text="Comma-separated list of available days (e.g., 'Monday, Tuesday, Friday')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time of availability (e.g., 05:00 PM)', null=True),
        ),
        migrations.AddField(
            model_name='doctordetails',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time of availability (e.g., 09:00 AM)', null=True),
        ),
    ]
