# Generated by Django 5.1.3 on 2025-01-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_story_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
