# Generated by Django 5.1.3 on 2025-01-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_consultation_is_booked'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.UniqueConstraint(fields=('user', 'doctor', 'consultation_time'), name='unique_consultation'),
        ),
    ]
