# Generated by Django 5.1.3 on 2025-01-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_consultation_unique_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='is_booked',
        ),
    ]
