# Generated by Django 5.1.3 on 2025-01-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_consultation_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='doctor_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
